apiVersion: v1
kind: Pod
metadata:
  name: file-reader
  namespace: robinhoodbot
spec:
  hostPID: true
  restartPolicy: Never
  containers:
    - name: nsenter
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
