apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robinhoodbot-data-nfs
  namespace: robinhoodbot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 3Gi
