apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robinhoodbot-data
  namespace: robinhoodbot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
