apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robinhoodbot-data-longhorn
  namespace: robinhoodbot
  annotations:
    numberOfReplicas: "3"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-redundant
  resources:
    requests:
      storage: 3Gi
