apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robinhoodbot-data-longhorn
  namespace: robinhoodbot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
